In [2]:
print('Helo World');

Helo World


In [5]:
Question = int(input('Enter any question : '))
if question > 3:
    print('I am greater then 3')
    print(question)
    
else:
    print('I am less then 3')
    print(question)

Enter any question : 12
I am grester then 3
12


In [ ]:
##f = open("demofile.txt","a")
##k = input('Enter data to be entered')
##f.write(k)
##f.close()



##f = open("demofile.txt", "r")
##print(f.read())

In [4]:

word_list= []
price_list= []

#iterate 4 times
var = input('Enter yes of no')
if var == 'yes':
    for i in range(1,3):
        print('Enter items Name  :')
        line = input() #take input
        print('Enter price of item in integer')
        price = input()
        word_list.extend(line)
        price_list.append(price)#append to the list
        f = open('demofile.txt', 'a')
        f.write("\n"+line+"\t"+price)
        f.close()
else:
    print('List of goods is')    
    




f = open('demofile.txt','r')
print(f.read())  
f.close()

Enter yes of noyes
Enter items Name  :
mango
Enter price of item in integer
120
Enter items Name  :
apple
Enter price of item in integer
90

mango	120
apple	90


# TUPLE

In [76]:
tuple1 = ("Zehra","Fatima","Muhammad","Ali","Hussain");
for i in tuple1:
    if "kamran" in tuple1:
        print("Zehra is present")
        break;
    else:
        print("Name : "+i)

Name : Zehra
Name : Fatima
Name : Muhammad
Name : Ali
Name : Hussain


In [ ]:
tuple1 = ("Zehra","Fatima","Muhammad","Ali","Hussain");
print(tuple1[-5:-1])

In [32]:
tuple1 = ("Zehra","Fatima","Muhammad","Ali","Hussain");
print(tuple1[1:3])

('Fatima', 'Muhammad')


# DIFFERENCE BETWEEN TUPLE AND LIST

In [94]:
l1 = ["Mango", "Banana","Cucumber","Potatoes"]

print(l1.pop(0))
print(l1.copy())
mylist = tuple(l1)
mylist[2]='Aleesha';
print(mylist)
print(type(mylist))

Mango
['Banana', 'Cucumber', 'Potatoes']


TypeError: 'tuple' object does not support item assignment

In [2]:
l1 = ["Mango", "Banana","Cucumber","Potatoes"]

print(l1.pop(0))
print(l1.copy())
mylist = list(l1)
mylist[2]='Aleesha';
print(mylist)
print(type(mylist))

Mango
['Banana', 'Cucumber', 'Potatoes']
['Banana', 'Cucumber', 'Aleesha']
<class 'list'>


In [10]:
list1 = [1,2,3,4,5]
list2 = ["Ali","Aleesha","Adeeba","Asad","Aaliya"]

for i in list1:
    list2.append(i)
    
print(list2)

['Ali', 'Aleesha', 'Adeeba', 'Asad', 'Aaliya', 1, 2, 3, 4, 5]


In [17]:
list1 = ["z", "b" , "c"]
list2 = [1, 2, 3]
list1.extend(list2)
print(list1)


None
['b', 'c', 'z', 1, 2, 3]


In [5]:
list2 = ["Zeeshan Ali","Syeda Aleesha","Adeeba Anjum","Hamdani Asad","Aaliya Asad"]
list2.sort(reverse=False)
print(list2)

['Aaliya Asad', 'Adeeba Anjum', 'Hamdani Asad', 'Syeda Aleesha', 'Zeeshan Ali']


In [5]:
def function(e):
    return len(e)

list2 = ["Zeeshan","Syeda","Adeeba","Hamdani","kamran"]
list2.sort(reverse=False,key=function)
print(list2)#sorts according to the length of the elements

['Syeda', 'Adeeba', 'kamran', 'Zeeshan', 'Hamdani']


In [3]:
Alphabets = {"A","B","C","D","E","F"}
Alphabets.update(["Ali","Amir"])
for i in Alphabets:
    print(i)

F
A
B
E
Amir
Ali
C
D


In [19]:
thisset = {'apple', 'banana', 'cherry'}
print(thisset)
var = input('Enter naem for discarding')
thisset.discard(var)
print(thisset)

{'banana', 'apple', 'cherry'}
Enter naem for discardingcherry
{'banana', 'apple'}


In [21]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

{1, 2, 3, 'a', 'b', 'c'}


In [23]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.symmetric_difference(y) 

print(z)

{'microsoft', 'google', 'cherry', 'banana'}


# DICTIONERIES

In [2]:
myfamily = {
    
    "Name :":"Ali",
    "Class :":"2nd Yrs",
    "Roll No. :":"02-131182-070"
    
    
    
}
for i in myfamily:
    print(i+""+myfamily[i])

Name :Ali
Class :2nd Yrs
Roll No. :02-131182-070


In [22]:
##Dynamic Dictionary
for i in range(0,3):#n-1 ka scene chlta hai yahan haio
    mySelf={
         "Name :": input('Name :'),
         "Class":input('Class :'),
         "Roll No. ":input('Roll No. :')
           }
    print(i+1,mySelf)
                


Name :Iqra
Class13
Roll No.1
1 {'Name :': 'Iqra', 'Class': '13', 'Roll No. ': '1'}
Name :Ali
Class14
Roll No.2
2 {'Name :': 'Ali', 'Class': '14', 'Roll No. ': '2'}
Name :Aleesha 
Class3
Roll No.12
3 {'Name :': 'Aleesha ', 'Class': '3', 'Roll No. ': '12'}


# import numpy as np (NUMPY) 

In [46]:
import numpy as np

text = '''
Text messages are used for personal, 
family, business and social purposes.
Governmental and non-governmental 
organizations use text messaging 
for communication between colleagues.
In the 2010s,the sending of short 
informal messages has become an
accepted part of many cultures,
as happened earlier with emailing.
This makes texting a quick and easy 
way to communicate with friends, 
family and colleagues,including in
contexts where a call would be impolite 
or inappropriate (e.g., calling very
late at night or when one knows the
other person is busy with family or
work activities). Like e-mail and 
voicemail, and unlike calls(in which the 
caller hopes to speak directly with the 
recipient),texting does not require the 
caller and recipient to both be free
at the same moment; this permits 
communication even between busy 
individuals. Text messages can also
be used to interact with automated 
systems, for example, to order products
or services from e-commerce websites, or 
to participate in online contests. 
Advertisers and service providers 
use direct text marketing to
send messages to mobile users about promotions, 
payment due dates, and other notifications 
instead of using postal , email, or voicemail.'''
s1 = text.split()    # .split() function splits the text in list
s2 = np.array(s1)
print(type(s2))
print(len(s2))

        
       
       


    


<class 'numpy.ndarray'>
184


In [60]:
import numpy as np
arr = np.array([1,2,3,4])#1d array(scalar)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
1
(4,)


In [64]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
2
(2, 3)


In [65]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int32
2
(3, 3)


# MYSQL DATABASE

In [8]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123"
)

print(mydb)

mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE PersonalInformation")

for x in mycursor:
    print(x)

In [11]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="PersonalInformation"
)

print(mydb)

mycursor = mydb.cursor()

for x in mycursor:
    print(x)

In [2]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

mycursor = mydb.cursor()

mycursor.execute("CREATE TABLE Students (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255), address VARCHAR(255))")


In [19]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
    print(x)

('students',)


In [29]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

mycursor = mydb.cursor()

#mycursor.execute("ALTER TABLE Students ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY")
mycursor.execute("SHOW TABLES")
for x in mycursor:
    print(x)
    print(mycursor)

('students',)
MySQLCursor: SHOW TABLES


In [21]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

sql = "INSERT INTO Students(name, address) VALUES (%s, %s)"
val = ("John", "Highway 21")
mycursor.execute(sql, val)

mydb.commit()

print(mycursor.rowcount, "record inserted.")

ProgrammingError: 1046 (3D000): No database selected

In [24]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


sql = "INSERT INTO Students (name, address) VALUES (%s, %s)"
val = [
  ('Peter', 'Lowstreet 4'),
  ('Amy', 'Apple st 652'),
  ('Hannah', 'Mountain 21'),
  ('Michael', 'Valley 345'),
  ('Sandy', 'Ocean blvd 2'),
  ('Betty', 'Green Grass 1'),
  ('Richard', 'Sky st 331'),
  ('Susan', 'One way 98'),
  ('Vicky', 'Yellow Garden 2'),
  ('Ben', 'Park Lane 38'),
  ('William', 'Central st 954'),
  ('Chuck', 'Main Road 989'),
  ('Viola', 'Sideway 1633')
]

mycursor.executemany(sql, val)

mydb.commit()

print(mycursor.rowcount, "was inserted.")

ProgrammingError: 1046 (3D000): No database selected

In [33]:
mycursor = mydb.cursor()

sql = "INSERT INTO Students (name, address) VALUES (%s, %s)"
val = ("Michelle", "Blue Village")
mycursor.execute(sql, val)

mydb.commit()

print("1 record inserted, ID:", mycursor.lastrowid)

1 record inserted, ID: 16


In [34]:

mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM Students")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('John', 'Highway 21', 1)
('John', 'Highway 21', 2)
('Peter', 'Lowstreet 4', 3)
('Amy', 'Apple st 652', 4)
('Hannah', 'Mountain 21', 5)
('Michael', 'Valley 345', 6)
('Sandy', 'Ocean blvd 2', 7)
('Betty', 'Green Grass 1', 8)
('Richard', 'Sky st 331', 9)
('Susan', 'One way 98', 10)
('Vicky', 'Yellow Garden 2', 11)
('Ben', 'Park Lane 38', 12)
('William', 'Central st 954', 13)
('Chuck', 'Main Road 989', 14)
('Viola', 'Sideway 1633', 15)
('Michelle', 'Blue Village', 16)


In [43]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

mycursor = mydb.cursor()

mycursor.execute("SELECT name, address FROM Students")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('John', 'Highway 21')
('John', 'Highway 21')
('Peter', 'Lowstreet 4')
('Amy', 'Apple st 652')
('Hannah', 'Mountain 21')
('Michael', 'Valley 345')
('Sandy', 'Ocean blvd 2')
('Betty', 'Green Grass 1')
('Richard', 'Sky st 331')
('Susan', 'One way 98')
('Vicky', 'Yellow Garden 2')
('Ben', 'Park Lane 38')
('William', 'Central st 954')
('Chuck', 'Main Road 989')
('Viola', 'Sideway 1633')
('Michelle', 'Blue Village')


In [50]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM Students")

myresult = mycursor.fetchmany(3);

print(myresult)

[('John', 'Highway 21', 1), ('John', 'Highway 21', 2), ('Peter', 'Lowstreet 4', 3)]


In [53]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "SELECT * FROM Students WHERE address ='Lowstreet 4'"

mycursor.execute(sql)

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('Peter', 'Lowstreet 4', 3)


In [59]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "SELECT * FROM Students WHERE name LIKE '%Peter%'"

mycursor.execute(sql)

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('Peter', 'Lowstreet 4', 3)


In [64]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "SELECT * FROM Students WHERE address = %s"
adr = ("Yellow Garden 2", )

mycursor.execute(sql, adr)

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('Vicky', 'Yellow Garden 2', 11)


In [67]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "SELECT * FROM Students ORDER BY address"

mycursor.execute(sql)

myresult = mycursor.fetchall()

for x in myresult:
     print(x)

('Amy', 'Apple st 652', 4)
('Michelle', 'Blue Village', 16)
('William', 'Central st 954', 13)
('Betty', 'Green Grass 1', 8)
('John', 'Highway 21', 1)
('John', 'Highway 21', 2)
('Peter', 'Lowstreet 4', 3)
('Chuck', 'Main Road 989', 14)
('Hannah', 'Mountain 21', 5)
('Sandy', 'Ocean blvd 2', 7)
('Susan', 'One way 98', 10)
('Ben', 'Park Lane 38', 12)
('Viola', 'Sideway 1633', 15)
('Richard', 'Sky st 331', 9)
('Michael', 'Valley 345', 6)
('Vicky', 'Yellow Garden 2', 11)


In [5]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "SELECT * FROM Students ORDER BY name DESC"

mycursor.execute(sql)

myresult = mycursor.fetchall()

for x in myresult:
     print(x)


In [73]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "DELETE FROM Students WHERE address = 'Highway 21'"

mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record(s) deleted")

2 record(s) deleted


In [ ]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

sql = "DROP TABLE Students"

mycursor.execute(sql)

In [4]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)

mycursor = mydb.cursor()

sql = "UPDATE Students SET address = 'Canyon 123' WHERE address = 'Valley 345'"

mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record(s) affected")

0 record(s) affected


In [8]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)
mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM   Students LIMIT 5")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(1, 'Peter', 'Lowstreet 4')
(2, 'Amy', 'Apple st 652')
(3, 'Hannah', 'Mountain 21')
(4, 'Michael', 'Valley 345')
(5, 'Sandy', 'Ocean blvd 2')


In [11]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root123",
  database="personalInformation"
)


mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM Students LIMIT 5 OFFSET 1")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

(2, 'Amy', 'Apple st 652')
(3, 'Hannah', 'Mountain 21')
(4, 'Michael', 'Valley 345')
(5, 'Sandy', 'Ocean blvd 2')
(6, 'Betty', 'Green Grass 1')


In [15]:
import mysql.connector

mydb = mysql.connector.connect(
     host="localhost",
    user="root",
    passwd="root123"
)
mycursor = mydb.cursor()
mycursor.execute("show databases")
for i in mycursor:
    print(i)

('information_schema',)
('mysql',)
('performance_schema',)
('personalinformation',)
('sakila',)
('sys',)
('world',)


# Image processing assignment 1

In [45]:
from PIL import Image
import numpy as np
import os


rootDir='Photos'

for dirName,subDirList,fileList in os.walk(rootDir):
    
    for fname in fileList:
        temp = Image.open(dirName+'/'+fname);
        resized = temp.resize((200,200))
        npImage +=np.array(resized)
        print(resized)
        print(npImage.ndim)
        print(npImage.size)
        print(npImage.shape)
    
    


<PIL.Image.Image image mode=RGB size=200x200 at 0x7F25770>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F17A90>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F17DF0>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F334D0>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F33890>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F17DF0>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F335B0>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F33890>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F17E90>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F17DF0>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F33530>
3
120000
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x7F335D0>
3
120000
(200, 200, 3)
<PIL.Image.Image

# Image processing assignment 2

In [4]:
from PIL import Image
import numpy as np
import os


def reSize(resizeArray):
    resizeArray = temp.resize((200,200))
    return resizeArray



def main(): 
    
    rootDir='Photos'
    npImage=0;
    for dirName,subDirList,fileList in os.walk(rootDir):
    
        for fname in fileList:
            temp = Image.open(dirName+'/'+fname);
            print(reSize(temp))
            npImage +=np.array(reSize(temp))
            print(npImage.shape)

        

        
    
if __name__ == "__main__":
    main()

<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x580F210>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6A80FD0>
(200, 200, 3)
<PIL.Image.Image image mode=RGB size=200x200 at 0x6